name: Security Scan

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  checkov:
    uses: clouddrove/github-shared-workflows/.github/workflows/checkov.yml@f6cad30db3bfad5fc248a08ab65ac82eb8dbcb82 # pinned to latest
    with:
      directory: '.'
      continue_on_error: 'true'
      skip_check: 'CKV_TF_1'
